# Generated by Django 2.1.5 on 2019-01-15 13:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('photos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('upload', models.FileField(upload_to='')),
                ('publish', models.BooleanField(default=False)),
                ('likes', models.ManyToManyField(through='photos.Like', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
