# Generated by Django 2.1.5 on 2019-01-15 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='publish',
            field=models.BooleanField(default=False),
        ),
    ]
