# Generated by Django 2.1.5 on 2019-01-14 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='publish',
            field=models.BooleanField(default=False),
        ),
    ]
