# Generated by Django 2.1.5 on 2019-01-14 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_document_publish'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Document',
            new_name='Photos',
        ),
    ]
